---
title: "piru community plots"
author: "Shane Dewees"
date: "3/30/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(here)
library(tidyverse)
library(lubridate)
```


Reading in data
```{r}
community_types <- read.csv(here("data", "community_types.csv"))
environmental_data <- read.csv(here("data", "par_soil_moisture.csv")) %>% 
  select(!community) %>% 
  full_join(community_types, join_by = "plot") %>% 
  mutate(date = mdy(date)) %>% 
  mutate(community = as.character(community))

#Coerced community to character so ggplot recognizes as discrete variable

survival_data <- read.csv(here("data", "survival.csv")) %>% 
  distinct() %>% 
  select(1:6) %>%
  mutate(species = case_when(species == "ADFA" ~ "adfa", 
                             species == "ARCA" ~ "arca",
                             species %in% c("ENCA", "ENFA") ~ "enca",
                             species == "ERFA" ~ "erfa",
                             species == "HEAR" ~ "hear",
                             species %in% c("MALA", "AMALA", "MALA?", "MELA") ~ "mala",
                             species %in% c("RHOU", "RHOV", "RHOB") ~ "rhov",
                             species == "SAAP" ~ "saap",
                             species %in% c("SALE", "SALEU")~ "sale",
                             species %in% c("SAME", "SAAME") ~ "same",
                             species %in% c("CECU", "GECU") ~ "cecu",
                             species %in% c("CEOL", "EOL", " CEOL") ~ "ceol",
                             species %in% c("RHIL", "RAIL") ~ "rhil",
                             TRUE ~ species)) %>% 
  group_by(plot, date, species) %>% 
  mutate(number_alive = sum(alive, na.rm = TRUE)) %>% 
  ungroup() %>% 
  select(!id & !alive & !notes) %>% 
  distinct() %>% 
  filter(species %in% c("sale", "saap", "arca", "erfa", "same", "enca", "adfa", "rhov", "mala", "ceol", "cecu", "rhil", "hear")) %>% 
  right_join(community_types, by = "plot") %>% 
  mutate(number_planted = case_when(community %in% c(1,2) & species == "sale" ~ 10,
                                    community %in% c(1,2) & species == "saap" ~ 10,
                                    community %in% c(1,2) & species == "arca" ~ 10,
                                    community %in% c(1,2) & species == "erfa" ~ 7,
                                    community %in% c(1,2) & species == "same" ~ 7,
                                    community %in% c(1,2) & species == "enca" ~ 10,
                                    community == 1 & species == "ceol" ~ 7,
                                    community == 1 & species == "cecu" ~ 5,
                                    community == 1 & species == "hear" ~ 7,
                                    community == 1 & species == "rhil" ~ 7,
                                    community == 2 & species == "adfa" ~ 9,
                                    community == 2 & species == "rhov" ~ 9,
                                    community == 2 & species == "mala" ~ 8,
                                    community == 3 & species == "ceol" ~ 13,
                                    community == 3 & species == "cecu" ~ 5,
                                    community == 3 & species == "hear" ~ 12,
                                    community == 3 & species == "rhil" ~ 12,
                                    community == 3 & species == "adfa" ~ 13,
                                    community == 3 & species == "rhov" ~ 13,
                                    community == 3 & species == "mala" ~ 12),
         number_planted = case_when(as.numeric(number_alive) > as.numeric(number_planted) ~ as.numeric(number_alive),
                                    as.numeric(number_alive) <= as.numeric(number_planted) ~ as.numeric(number_planted)),
         percent_alive = number_alive/number_planted * 100,
         date = mdy(date),
         month = month(date, label = TRUE),
         community = case_when(community == 1 ~ "sage_obligate_seeder/resprouter",
                               community == 2 ~ "sage_facultative_resprouter",
                               community == 3 ~ "chaparral_only"))

survival_summary <- survival_data %>% 
  group_by(community, month, species) %>% 
  summarise(mean_survival = mean(percent_alive, na.rm = TRUE)) %>% 
  filter(mean_survival != "NaN")
  


ggplot(survival_summary, aes(x = species, y = mean_survival, col= as.factor(community)), size = 5) +
  geom_point()+
  facet_wrap(~month) +
  theme_classic() +
  theme(text = element_text(size = 10))
```

Caluclate % of ambient par in plots
```{r}
environmental_data <- environmental_data %>% 
  mutate(par_prop = 100 - (par_plot / par_ambient) * 100)
```


Anova and Tukeys test to test for significance of soil moisture and %ambient par between communities
```{r}
date_key <- environmental_data %>% 
    group_by(date) %>% 
    summarise()

i <- 1

while(i <= nrow(date_key)){
  temp <- environmental_data %>% 
    filter(date == date_key$date[i])
    
  soil_moisture_anova <- aov(soil_moisture ~ factor(community), data = temp)
  soil_moisture_tukey <- TukeyHSD(soil_moisture_anova, conf.level = .95)
    
  par_prop_anova <- aov(par_prop ~ factor(community), data = temp)
  par_prop_tukey <- TukeyHSD(par_prop_anova, conf.level = .95)
    
  assign(paste("soil_moisture_anova", date_key$date[i], sep = "_"), soil_moisture_anova)
  assign(paste("soil_moisture_tukey", date_key$date[i], sep = "_"), soil_moisture_tukey)
   assign(paste("par_prop_anova", date_key$date[i], sep = "_"), par_prop_anova)
  assign(paste("par_prop_tukey", date_key$date[i], sep = "_"), par_prop_tukey)
  
  i = i + 1
}
  
rm(soil_moisture_anova)
rm(soil_moisture_tukey)
rm(par_prop_anova)
rm(par_prop_tukey)
rm(temp)
rm(i)
```

Make some ggplots of %ambient par and soil moisture to visualize data
```{r}
#Scatter plot of %ambient par vs soil moisture with color indicating community
ggplot(data = environmental_data) +
  geom_point(mapping = aes(x = par_prop, y = soil_moisture, color = community), alpha = .5) +
  geom_smooth(mapping = aes(x = par_prop, y = soil_moisture, color = community, fill = community), method = "lm", formula = y ~ x, alpha = .05) +
  facet_wrap(~date)+
  theme_classic() +
  labs(caption = "Figure 1: Percent of ambient par blocked by plants versus soil moisture for three community types",
       x = "Percent of Ambient Par Blocked",
       y = "Soil Moisture",
       color = "Community Type:",
       fill = "") +
  guides(fill = FALSE) +
  theme(plot.caption = element_text(face = "bold", size = 11, hjust = 0),
        legend.position = "top",
        axis.title = element_text(size = 10),
        axis.text = element_text(size = 7))

#Jitter plot for soil moisture
ggplot(data = environmental_data) +
  geom_jitter(mapping = aes(x = community, y = soil_moisture), width = .2, alpha = .5, color = "blue") +
  facet_wrap(~date) +
  theme_classic() +
  labs(caption = "Figure 2: Soil moisture across community types.",
       x = "Community Type",
       y = "Soil Moisture") +
  theme(plot.caption = element_text(face = "bold", size = 11, hjust = 0),
        legend.position = "top",
        axis.title = element_text(size = 10),
        axis.text = element_text(size = 7))

#Jitter plot for par_prop
ggplot(data = environmental_data) +
  geom_jitter(mapping = aes(x = community, y = par_prop), width = .2, alpha = .5, color = "orange") +
  facet_wrap(~date) +
  theme_classic() +
  labs(caption = "Figure 3: Proportion of ambient PAR blocked across community types.",
       x = "Community Type",
       y = "Proportion of PAR Blocked") +
  theme(plot.caption = element_text(face = "bold", size = 11, hjust = 0),
        legend.position = "top",
        axis.title = element_text(size = 10),
        axis.text = element_text(size = 7))
```

