---
title: "Untitled"
output: html_document
date: "2024-01-09"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(here)
library(tidyverse)
library(lubridate)
```

## Cleaning Par data

```{r}
par_may_2023 <- read.csv(here("data", "raw_data", "par_may_2023.csv")) %>% 
  separate(Plot, into = c("plot", "plant"), sep = "-") %>% 
  mutate(par = PAR.Plot/PAR.Amb,
         date = mdy(Date)) %>%  
  select(plot, par, date)

par_soil_moisture <- read.csv(here("data", "raw_data", "par_soil_moisture.csv")) %>% 
  mutate(date = str_replace(date, "15-Jul", "7/15/2022"),
         date = str_replace(date, "21-Nov", "11/21/2022")) %>% 
  mutate(par = par_plot/par_ambient,
         date = mdy(date)) %>% 
  select(plot, par, date)

par_sept_2023 <- read.csv(here("data", "raw_data", "sept_par_soil.csv")) %>% 
  rename(plot = Plot) %>% 
  mutate(par = PAR.plot/PAR.ambient,
         date = mdy(Date)) %>% 
  select(plot, par, date) %>% 
  drop_na()

par <- rbind(par_soil_moisture, par_may_2023, par_sept_2023) %>% 
  mutate(plot = as.numeric(plot))

write.csv(par, here("data", "clean_data", "par_clean.csv"))
```

## Cleaning soil moisture data

```{r}
par_soil_moisture2 <- read.csv(here("data", "raw_data", "par_soil_moisture.csv")) %>% 
  mutate(date = str_replace(date, "15-Jul", "7/15/2022"),
         date = str_replace(date, "21-Nov", "11/21/2022")) %>% 
  mutate(date = mdy(date)) %>% 
  select(plot, soil_moisture, date) %>% 
  drop_na()

soil_sept_2023 <- read.csv(here("data", "raw_data", "sept_par_soil.csv")) %>% 
  rename(plot = Plot,
         soil_moisture = X..moisture) %>% 
  mutate(date = mdy(Date)) %>% 
  select(plot, soil_moisture, date) %>% 
  drop_na()

soil_moisture <- rbind(par_soil_moisture2, soil_sept_2023)
write.csv(soil_moisture, here("data", "clean_data", "soil_moisture_clean.csv"))
```

