---
title: "Untitled"
output: html_document
date: "2023-03-01"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(survival)
library(lubridate)
library(ggsurvfit)
library(gtsummary)
library(survminer)
library(ggfortify)
library(coxme)
```

```{r}
survival_data <- read.csv(here("data", "clean_data", "kaplan_survival_data.csv")) %>% 
  select(!X) %>% 
  mutate(month = month(start_date),
         year = year(start_date))

survival_sum <- survival_data %>% 
  filter(start_time == 0) %>% 
  mutate(alive = case_when(dead == 0 ~ 1,
                           dead == 1 ~ 0)) %>% 
  group_by(plot) %>% 
  reframe(plants_alive = sum(alive))

species_sum <- survival_data %>% 
  filter(start_time == 0) %>% 
  filter(start_time == 0) %>% 
  mutate(alive = case_when(dead == 0 ~ 1,
                           dead == 1 ~ 0)) %>%
  group_by(plot, species) %>% 
  reframe(alive = sum(alive)) %>% 
  left_join(survival_sum, by = "plot") %>%
  mutate(simpsons = (alive/plants_alive)^2) %>% 
  group_by(plot) %>% 
  reframe(simpsons = sum(simpsons),
          plants_alive = mean(plants_alive) )

ggplot(species_sum, aes(x = plants_alive, y = simpsons))+
  geom_point()
summary(glm(simpsons~plants_alive, data = species_sum ))

chap_sum <- survival_data %>% 
  filter(start_time == 0 & species %in% c("rhov", "mala", "adfa", "hear", "rhil", "cecu", "ceol"))%>% 
  mutate(alive = case_when(dead == 0 ~ 1,
                           dead == 1 ~ 0)) %>% 
  group_by(plot) %>% 
  reframe(plants_alive = sum(alive))

sage_sum <- survival_data %>% 
  filter(start_time == 0 & species %in% c("arca", "erfa", "enca", "saap", "sale", "same"))%>% 
  mutate(alive = case_when(dead == 0 ~ 1,
                           dead == 1 ~ 0)) %>% 
  group_by(plot) %>% 
  reframe(plants_alive = sum(alive))

survival_density <- survival_data %>% 
  filter(start_time != 0 & end_time < 365) %>% 
  left_join(species_sum, by = "plot") %>% 
  mutate(simpsons = scale(simpsons))

chap_density <- survival_data %>% 
  filter(start_time != 0) %>% 
  left_join(chap_sum, by = "plot") %>% 
  mutate(plants_alive = replace_na(plants_alive, 0))

sage_density <- survival_data %>% 
  filter(start_time != 0) %>% 
  left_join(sage_sum, by = "plot") %>% 
  mutate(plants_alive = replace_na(plants_alive, 0))

par <- read.csv(here("data", "clean_data", "par_clean.csv")) %>% 
  select(!X) %>% 
  group_by(plot, date) %>% 
  reframe(par = mean(par, na.rm = T)) %>% 
  mutate(month = month(date),
         year = year(date))

soil_moisture <- read.csv(here("data", "clean_data", "soil_moisture_clean.csv")) %>% 
  select(!X) %>%
  group_by(plot, date) %>% 
  reframe(soil_moisture = mean(soil_moisture, na.rm = T)) %>% 
  mutate(month = month(date),
         year = year(date))

temp_vpd <- read.csv(here("data", "clean_data", "temp_vpd_predicted.csv")) %>% 
  select(!X)

survival_temp_prep <- survival_data %>% 
  select(plot, start_date, end_date) %>% 
  distinct() %>% 
  full_join(temp_vpd, by = "plot") %>% 
  filter(date >= start_date & date < end_date) %>% 
  group_by(plot, start_date, end_date) %>% 
  reframe(temperature = mean(temperature),
          vpd = mean(vpd))

survival_environmental <- survival_density %>% 
  left_join(par, by = c("plot", "month", "year")) %>% 
  left_join(soil_moisture, by = c("plot", "month", "year")) %>% 
  left_join(survival_temp_prep, by = c("plot", "start_date", "end_date")) %>% 
  mutate(community = as.factor(community)) %>% 
  filter(end_time < 365)
```

## General Survival Figures

```{r}
autoplot(survfit(Surv(start_time, end_time, dead) ~ community_type, id = unique_id, data = survival_data)) + ylim(0,1) +
  geom_vline(xintercept = 146) +
  geom_vline(xintercept = 203)

autoplot(survfit(Surv(start_time, end_time, dead) ~ community + chap_type, id = unique_id, data = survival_environmental_chap))

autoplot(survfit(Surv(start_time, end_time, dead) ~ community, id = unique_id, data = survival_data %>% filter(species == "rhov")))
autoplot(survfit(Surv(start_time, end_time, dead) ~ community, id = unique_id, data = survival_data %>% filter(species == "adfa")))
autoplot(survfit(Surv(start_time, end_time, dead) ~ community, id = unique_id, data = survival_data %>% filter(species == "mala")))
autoplot(survfit(Surv(start_time, end_time, dead) ~ community, id = unique_id, data = survival_data %>% filter(species == "ceol")))
autoplot(survfit(Surv(start_time, end_time, dead) ~ community, id = unique_id, data = survival_data %>% filter(species == "cecu")))
autoplot(survfit(Surv(start_time, end_time, dead) ~ community, id = unique_id, data = survival_data %>% filter(species == "hear")))
autoplot(survfit(Surv(start_time, end_time, dead) ~ community, id = unique_id, data = survival_data %>% filter(species == "rhil")))

autoplot(survfit(Surv(start_time, end_time, dead) ~ 1, id = unique_id, data = survival_data %>% filter(species == "arca"))) + ylim(0,1)
autoplot(survfit(Surv(start_time, end_time, dead) ~ 1, id = unique_id, data = survival_data %>% filter(species == "erfa"))) + ylim(0,1)
autoplot(survfit(Surv(start_time, end_time, dead) ~ 1, id = unique_id, data = survival_data %>% filter(species == "enca"))) + ylim(0,1)
autoplot(survfit(Surv(start_time, end_time, dead) ~ 1, id = unique_id, data = survival_data %>% filter(species == "sale"))) + ylim(0,1)
autoplot(survfit(Surv(start_time, end_time, dead) ~ 1, id = unique_id, data = survival_data %>% filter(species == "saap"))) + ylim(0,1)
autoplot(survfit(Surv(start_time, end_time, dead) ~ 1, id = unique_id, data = survival_data %>% filter(species == "same"))) + ylim(0,1)
```
## Testing if there is a significant effect post-transplant shock density


```{r}
cox.zph(coxme(Surv(start_time, end_time, dead) ~ plants_alive + (1|plot), data = survival_density %>% filter(dead == 1 |end_date == "2022-11-21") %>% mutate(start_time = 0)))
coxme(Surv(start_time, end_time, dead) ~ plants_alive + (1|plot), data = survival_density %>% filter(dead == 1 |end_date == "2022-11-21") %>% mutate(start_time = 0)) %>%  tbl_regression(exp = T)

cox.zph(coxme(Surv(start_time, end_time, dead) ~ plants_alive + (1|plot), data = survival_density %>% filter(community_type == "sage") %>%
                filter(dead == 1 |end_date == "2022-11-21") %>%  mutate(start_time = 0)))
plot(cox.zph(coxme(Surv(start_time, end_time, dead) ~ plants_alive + (1|plot), data = survival_density %>% filter(community_type == "sage") %>%
                filter(dead == 1 |end_date == "2022-11-21") %>%  mutate(start_time = 0))))
cox.zph(coxme(Surv(start_time, end_time, dead) ~ plants_alive + (1|plot), data = survival_density %>% filter(community_type == "chap") %>%
                filter(dead == 1 |end_date == "2022-11-21") %>% mutate(start_time = 0)))

coxme(Surv(start_time, end_time, dead) ~ plants_alive + (1|plot), data = survival_density %>% filter(community_type == "sage") %>% 
        filter(dead == 1 |end_date == "2022-11-21") %>%  mutate(start_time = 0)) %>% tbl_regression(exp = T)

coxme(Surv(start_time, end_time, dead) ~ plants_alive + (1|plot), data = survival_density %>% filter(community_type == "chap") %>% 
        filter(dead == 1 |end_date == "2022-11-21") %>% mutate(start_time = 0)) %>% tbl_regression(exp = T)
```

```{r}
survival_environmental_narrow <- survival_environmental %>% filter(date.y != "2022-06-09") %>% 
  mutate(par = scale(par),
         soil_moisture = scale(soil_moisture),
         temperature = scale(temperature),
         vpd = scale(vpd))
cox.zph(coxme(Surv(start_time, end_time, dead) ~ soil_moisture + par + plants_alive + (1|plot),
              data = survival_environmental_narrow))
plot(cox.zph(coxme(Surv(start_time, end_time, dead) ~ soil_moisture + par + plants_alive + (1|plot),
              data = survival_environmental_narrow)))
cox.zph(coxme(Surv(start_time, end_time, dead) ~ soil_moisture + par + plants_alive + (1|plot),
              data = survival_environmental_narrow %>% filter(end_time <240)))
cox.zph(coxme(Surv(start_time, end_time, dead) ~ soil_moisture + par + plants_alive + (1|plot),
              data = survival_environmental_narrow %>% filter(end_time > 240 & end_time < 280)))
cox.zph(coxme(Surv(start_time, end_time, dead) ~ soil_moisture + par + plants_alive + (1|plot),
              data = survival_environmental_narrow %>% filter(end_time > 280)))
coxme(Surv(start_time, end_time, dead) ~ soil_moisture + par + plants_alive + (1|plot),
              data = survival_environmental_narrow %>% filter(end_time <240)) %>% 
  tbl_regression(exp = T)
coxme(Surv(start_time, end_time, dead) ~ soil_moisture + par + plants_alive + (1|plot),
              data = survival_environmental_narrow %>% filter(end_time > 240 & end_time < 280)) %>% 
  tbl_regression(exp = T)
coxme(Surv(start_time, end_time, dead) ~ soil_moisture + par + plants_alive + (1|plot),
              data = survival_environmental_narrow %>% filter(end_time > 280)) %>% 
  tbl_regression(exp = T)

cox.zph(coxme(Surv(start_time, end_time, dead) ~ soil_moisture + par + plants_alive + (1|plot),
              data = survival_environmental_narrow %>% filter(community_type == "sage" & end_time > 204)))
plot(cox.zph(coxme(Surv(start_time, end_time, dead) ~ soil_moisture + par + plants_alive + (1|plot),
              data = survival_environmental_narrow %>% filter(community_type == "sage" & end_time > 204))))
cox.zph(coxme(Surv(start_time, end_time, dead) ~ soil_moisture + par + plants_alive + (1|plot),
              data = survival_environmental_narrow %>% filter(community_type == "sage"& end_time >204 & end_time < 280)))
cox.zph(coxme(Surv(start_time, end_time, dead) ~ soil_moisture + par + plants_alive + (1|plot),
              data = survival_environmental_narrow %>% filter(community_type == "sage"& end_time > 280)))
coxme(Surv(start_time, end_time, dead) ~ soil_moisture + par + plants_alive + (1|plot),
              data = survival_environmental_narrow %>% filter(community_type == "sage"& end_time > 204 & end_time <280)) %>% 
  tbl_regression(exp = T)
coxme(Surv(start_time, end_time, dead) ~ soil_moisture + par + plants_alive + (1|plot),
              data = survival_environmental_narrow %>% filter(community_type == "sage" & end_time >280)) %>%
  tbl_regression(exp = T)


cox.zph(coxme(Surv(start_time, end_time, dead) ~ soil_moisture + par + plants_alive + (1|plot),
              data = survival_environmental_narrow %>% filter(community_type == "chap")))
plot(cox.zph(coxme(Surv(start_time, end_time, dead) ~ soil_moisture + par + plants_alive + (1|plot),
              data = survival_environmental_narrow %>% filter(community_type == "chap"))))
cox.zph(coxme(Surv(start_time, end_time, dead) ~ soil_moisture + par + plants_alive + (1|plot),
              data = survival_environmental_narrow %>% filter(community_type == "chap" & end_time < 280)))
coxme(Surv(start_time, end_time, dead) ~ soil_moisture + par + plants_alive + (1|plot),
              data = survival_environmental_narrow %>% filter(community_type == "chap" & end_time < 280)) %>% 
  tbl_regression(exp = T)
coxme(Surv(start_time, end_time, dead) ~ soil_moisture + par + plants_alive + (1|plot),
              data = survival_environmental_narrow %>% filter(community_type == "chap" & end_time > 280)) %>% 
  tbl_regression(exp = T)

```

```{r}
soil_density <- soil_moisture %>% 
  group_by(date) %>% 
  mutate(soil_moisture = scale(soil_moisture)) %>% 
  ungroup() %>% 
  left_join(species_sum, by = "plot")

summary(glm(soil_moisture ~ plants_alive, data = soil_density %>% filter(date == "2022-05-06")))
summary(glm(soil_moisture ~ plants_alive, data = soil_density %>% filter(date == "2022-06-09")))
summary(glm(soil_moisture ~ plants_alive, data = soil_density %>% filter(date == "2022-07-15")))
summary(glm(soil_moisture ~ plants_alive, data = soil_density %>% filter(date == "2022-09-08")))
summary(glm(soil_moisture ~ plants_alive, data = soil_density %>% filter(date == "2022-10-19")))
summary(glm(soil_moisture ~ plants_alive, data = soil_density %>% filter(date == "2022-11-21")))

par_density <- par %>% 
  group_by(date) %>% 
  mutate(par = scale(par)) %>% 
  ungroup() %>% 
  left_join(species_sum, by = "plot") %>% 
  mutate(par = as.numeric(par)) %>% 
  drop_na()f

summary(glm(par ~ plants_alive, data = par_density %>% filter(date == "2022-05-06")))
summary(glm(par ~ plants_alive, data = par_density %>% filter(date == "2022-06-09")))
summary(glm(par ~ plants_alive, data = par_density %>% filter(date == "2022-07-15")))
summary(glm(par~plants_alive, data = par_density %>% filter(date == "2022-08-05")))
summary(glm(par ~ plants_alive, data = par_density %>% filter(date == "2022-09-08")))
summary(glm(par ~ plants_alive, data = par_density %>% filter(date == "2022-10-19")))
```

```{r}
soil_transplant <- soil_moisture %>% 
  filter(date == "2022-04-05") %>% 
  left_join(par, by = c("plot", "date")) %>% 
  left_join(species_sum, by = "plot")

summary(lm(plants_alive ~ soil_moisture, data = soil_transplant))

ggplot(soil_transplant, aes(x = soil_moisture, y = simpsons))+
  geom_point()+ 
  geom_smooth(method = "lm")+
  theme_classic()
```







