---
title: "Untitled"
output: html_document
date: "2024-01-17"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(here)
library(tidyverse)
library(lubridate)
library(lme4)
```

```{r}
cover <- read.csv(here("data", "clean_data", "percent_cover_clean.csv")) %>% 
  filter(date == "2023-03-09" & species == "Sage")
gsw <- read.csv(here("data", "clean_data", "gsw_clean.csv"))
fungus <- read.csv(here("data", "clean_data", "fungus_clean.csv")) %>% 
  mutate(plot = as.numeric(plot),
         id = as.numeric(id),
         plot = case_when(plot == 2408 ~ 2404, 
                          T ~ plot)) %>% 
  drop_na()
height <- read.csv(here("data", "clean_data", "height_clean.csv"))
nutrients <- read.csv(here("data", "clean_data", "nutrients_clean.csv")) %>% 
  group_by(plot) %>% 
  reframe(nitrogen = mean(Total.N),
          phosphorous = mean(P),
          potasium = mean(K))

soil_moisture <- read.csv(here("data", "clean_data", "soil_moisture_clean.csv"))
soil_moisture_nov <- soil_moisture %>% 
  filter(date == "2022-09-08") %>%
  group_by(plot) %>% 
  reframe(soil_moisture = mean(soil_moisture))

fungus_all <- fungus %>% 
  left_join(gsw, by = c("plot", "id")) %>% 
  drop_na() %>% 
  left_join(nutrients, by = "plot") %>% 
  left_join(cover, by = "plot")

fungus_height <- fungus %>% 
  left_join(height, by = c("plot", "id")) %>% 
  drop_na() %>% 
  left_join(nutrients, by = "plot") %>% 
  left_join(soil_moisture_nov, by = "plot")

fungus_nutrients <- fungus %>% 
  left_join(nutrients, by = "plot")

fungus_soil <- fungus %>% 
  left_join(soil_moisture_nov, by = "plot") %>% 
  left_join(nutrients, by = "plot")

fungus_cover <- fungus %>% 
  left_join(cover, by = "plot") %>% 
  mutate(percent_cover = case_when(is.na(percent_cover) == T ~ 0,
                                   T ~ percent_cover))
```


```{r}
summary(glmer(gsw~vesicle_colonization + potasium + nitrogen + percent_cover + (1|plot), data = fungus_all))
sjPlot::plot_model(glmer(gsw~vesicle_colonization + potasium + nitrogen + percent_cover + (1|plot), data = fungus_all))
summary(glm(gsw~arbuscule_colonization+ nitrogen + percent_cover, data = fungus_all))
summary(glm(gsw~hyphae_colonization+ nitrogen + percent_cover, data = fungus_all))
summary(glm(gsw~vesicle_colonization + arbuscule_colonization + hyphae_colonization, data = fungus_all))
```
```{r}
summary(glm(height_cm~vesicle_colonization + nitrogen, data = fungus_height %>% filter(date.y == "5/17/2023")))
summary(glm(height_cm~arbuscule_colonization, data = fungus_height %>% filter(date.y == "5/17/2023")))
summary(glm(height_cm~hyphae_colonization, data = fungus_height %>% filter(date.y == "5/17/2023")))
summary(glm(height_cm~vesicle_colonization + arbuscule_colonization + hyphae_colonization, data = fungus_height %>% filter(date.y == "5/17/2023")))

ggplot(fungus_height %>% filter(date.y == "5/17/2023"), aes(x = arbuscule_colonization, y = height_cm))+
  geom_point()+
  geom_smooth(method = "glm")+
  theme_classic()
```

```{r}
fungal_growth <- fungus_height %>% 
  mutate(month = month(mdy(date.y), label = T)) %>% 
  filter(month != "Mar") %>% 
  pivot_wider(id_cols = c("plot", "id", "vesicle_colonization", "arbuscule_colonization", "hyphae_colonization", "nitrogen", "soil_moisture"),
              names_from = month, values_from = height_cm) %>% 
  mutate(growth = (log(Sep) - log(May))/(128))

summary(glm(growth ~ vesicle_colonization, data = fungal_growth))
summary(glm(growth ~ arbuscule_colonization, data = fungal_growth))
summary(glm(growth ~ hyphae_colonization, data = fungal_growth))

summary(glm(growth ~ vesicle_colonization + arbuscule_colonization + hyphae_colonization, data = fungal_growth))

summary(glm(growth ~ vesicle_colonization + nitrogen, data = fungal_growth))
summary(glm(growth ~ arbuscule_colonization + nitrogen, data = fungal_growth))
summary(glm(growth ~ hyphae_colonization + nitrogen, data = fungal_growth))

summary(glm(growth ~ vesicle_colonization + soil_moisture, data = fungal_growth))
summary(glm(growth ~ arbuscule_colonization + soil_moisture, data = fungal_growth))
summary(glm(growth ~ hyphae_colonization + soil_moisture, data = fungal_growth))

summary(glm(growth ~ vesicle_colonization + soil_moisture + nitrogen, data = fungal_growth))
summary(glm(growth ~ arbuscule_colonization + soil_moisture + nitrogen, data = fungal_growth))
summary(glm(growth ~ hyphae_colonization + soil_moisture + nitrogen, data = fungal_growth))
```

```{r}
summary(glm(vesicle_colonization ~ soil_moisture, data = fungus_soil))
summary(glm(arbuscule_colonization ~ soil_moisture, data = fungus_soil))
summary(glm(hyphae_colonization ~ soil_moisture, data = fungus_soil))

summary(glm(vesicle_colonization ~ soil_moisture + nitrogen, data = fungus_soil))
summary(glm(arbuscule_colonization ~ soil_moisture + nitrogen, data = fungus_soil))
summary(glm(hyphae_colonization ~ soil_moisture + nitrogen, data = fungus_soil))
```

```{r}
summary(glm(vesicle_colonization ~ percent_cover, data = fungus_cover))
summary(glm(arbuscule_colonization ~ percent_cover, data = fungus_cover))
summary(glm(hyphae_colonization ~ percent_cover, data = fungus_cover))
```

```{r}
summary(glm(vesicle_colonization ~ nitrogen, data = fungus_nutrients))
summary(glm(arbuscule_colonization ~ nitrogen, data = fungus_nutrients))
summary(glm(hyphae_colonization ~ nitrogen, data = fungus_nutrients))

summary(glm(vesicle_colonization ~ phosphorous, data = fungus_nutrients))
summary(glm(arbuscule_colonization ~ phosphorous, data = fungus_nutrients))
summary(glm(hyphae_colonization ~ phosphorous, data = fungus_nutrients))

summary(glm(vesicle_colonization ~ nitrogen + phosphorous, data = fungus_nutrients))
summary(glm(arbuscule_colonization ~ nitrogen + phosphorous, data = fungus_nutrients))
summary(glm(hyphae_colonization ~ nitrogen + phosphorous, data = fungus_nutrients))
```

```{r}
summary(glm(vesicle_colonization ~ percent_cover + nitrogen + phosphorous + potasium, data = fungus_all))
summary(glm(arbuscule_colonization ~ percent_cover + nitrogen, data = fungus_all))
summary(glm(hyphae_colonization ~ percent_cover + nitrogen, data = fungus_all))
```

