---
title: "Untitled"
author: "Shane Dewees"
date: "2023-01-30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)
library(lubridate)
library(pls)
```

```{r}
plant_traits <- read.csv(here("data", "plant_traits.csv")) %>% 
  rename(species = Species,
         sla = Specific.Leaf.Area..mm.2.g..1.,
         leaf_water_content = Leaf.Water.Content....,
         ldmc = Leaf.Dry.Matter.Content..LDMC...g.g.,
         leaf_thickness = Leaf.Thickness..mm.,
         leaf_c_n = Leaf.C.N..kg.kg.,
         wue = Integrated.Water.Use.Efficiency..13C.in.ppm.,
         leaf_c_percentage = Leaf.C.Percentage....,
         leaf_n_percentage = Leaf.N.Percentage....,
         leaf_n_area = Leaf.N.Area..g.m2.,
         leaf_n_content_leaf_dry_mass = Leaf.N.Content.Leaf.Dry.Mass..g.N.g.1.DW.,
         leaf_c_area = Leaf.Carbon.Content.Per.Area..kg.C.per.m2.,
         form = Form,
         resprouter = resprouter.,
         seeder = seeder.,
         life_span = max.lifespan..years.,
         altitude_high = Altitude.High..m.,
         south_latitude = Latitude.S..deg.,
         north_latitude = Latitude.N..deg.,
         flowering_season = Flowering.Season,
         flowering_first_month = Flowering.time..1st.month.,
         flowering_last_month = Flowering.time..last.month.,
         flowering_duration = Flowering.Period.Length..d.,
         growth_rate = growth.rate..category.,
         crown_height = Crown.Height..m.,
         max_height = Max.Height..m.,
         crown_width = Crown.Width..m.,
         leaf_persistance = Leaf.persistence,
         petiole_length = Petiole.Length..cm.,
         leaf_lamina_length = Leaf.Lamina.Length..cm.,
         leaf_width = Leaf.Width..cm.,
         dispersal_mechanism = dispersal.mech,
         time_reproduction = Time.to.Reproduction..mo.,
         seed_longevity = Seed.longevity..category.,
         seed_dry_mass = Seed.Dry.Mass..mg.,
         wood_density = Wood.Density.Specific.Gravity..g.cm.3.) %>% 
  dplyr::select(species,
         sla,
         leaf_water_content,
         ldmc,
         leaf_thickness,
         leaf_c_n,
         wue,
         leaf_c_percentage,
         leaf_n_percentage,
         leaf_n_area,
         leaf_n_content_leaf_dry_mass,
         leaf_c_area,
         growth_rate,
         crown_height,
         max_height,
         crown_width,
         petiole_length,
         leaf_lamina_length,
         leaf_width,
         wood_density) %>% 
  mutate(species = case_when(species == "Adenostoma fasciculatum" ~ "adfa",
                             species == "Artemisia californica" ~ "arca",
                             species == "Ceanothus cuneatus" ~ "cecu",
                             species == "Ceanothus oliganthus" ~ "ceol",
                             species == "Encelia californica" ~ "enca",
                             species == "Eriogonum fasciculatum" ~ "erfa",
                             species == "Heteromeles arbutifolia" ~ "hear",
                             species == "Malosma laurina" ~ "mala",
                             species == "Rhamnus ilicifolia" ~ "rhil",
                             species == "Rhus ovata" ~ "rhov",
                             species == "Salvia apiana" ~ "saap",
                             species == "Salvia leucophylla" ~ "sale",
                             species == "Salvia mellifera" ~ "same"))

leaf_traits <- plant_traits %>% 
  dplyr::select(species,
                sla,
                ldmc,
                leaf_thickness,
                leaf_c_n,
                leaf_n_area,
                leaf_c_area,
                petiole_length,
                leaf_lamina_length,
                leaf_width)

leaf_traits_pca_input <- leaf_traits %>% 
  column_to_rownames(var = "species")

leaf_traits_pca <- leaf_traits_pca_input %>% 
  prcomp(center = TRUE, scale. = TRUE)
summary(leaf_traits_pca)
autoplot(leaf_traits_pca, loadings = T, loadings.label = T, label = T, colour = "darkgrey", loadings.colour = "black",
         loadings.label.colour = "black", loadings.repel = T) +
  theme_classic() +
  xlim(-0.75, 0.75)

plant_traits_output <- as.data.frame(leaf_traits_pca[["x"]]) %>% 
  rownames_to_column(var = "species") %>% 
  dplyr::select(species, PC1, PC2) %>% 
  left_join(plant_traits, by = "species") %>% 
  dplyr::select(species, 
                PC1, 
                PC2,
                wue,
                crown_height,
                crown_width,
                wood_density)

#write.csv(plant_traits_output, here("data", "planted_plant_traits.csv"))
```

```{r}
landscape_pca <- landscape_traits %>% 
  select(!species) %>% 
  prcomp(center = TRUE, scale. = TRUE)
summary(landscape_pca)

barplot(landscape_pca$rotation[,1], las = 2)
traits_pca_input <- plant_traits %>% 
  column_to_rownames(var = "species")
community_pca <- predict(landscape_pca, traits_pca_input) %>% 
  as.data.frame() %>% 
  rownames_to_column(var = "species")

ggplot(community_pca, aes(x = PC2, y = PC1))+
  geom_text(aes(label = species))+
  theme_minimal()

total_species_survival <- survival_data %>% 
  filter(date == "2022-11-21") %>% 
  group_by(species) %>% 
  summarise(number_alive = sum(number_alive),
            total_planted = sum(number_planted)) %>% 
  ungroup() %>% 
  mutate(proportion_alive = number_alive/total_planted) %>% 
  left_join(community_pca, by = "species")

summary(lm(proportion_alive~PC1, data = total_species_survival))
summary(lm(proportion_alive~PC2, data = total_species_survival))

pc1_graph <- ggplot(total_species_survival, aes(x= PC1, y = proportion_alive))+
  geom_text(aes(label = species))+
  geom_text(aes(x = -3, y = 0.5, label = "r^2 == 0.377"), parse = T)+
  geom_text(aes(x = -3, y = 0.47, label = "p = 0.0255"))+
  geom_smooth(method = "glm")+
  theme_classic()+
  labs(y = "Proportion alive")

pc2_graph <- ggplot(total_species_survival, aes(x= PC2, y = proportion_alive))+
  geom_text(aes(label = species))+
  geom_text(aes(x = 2.5, y = 0.5, label = "r^2 == 0.216"), parse = T)+
  geom_text(aes(x = 2.5, y = 0.45, label = "p = 0.109"))+
  geom_smooth(method = "lm")+
  theme_classic()+
  labs(y = "Proportion alive")

pc1_loadings <- landscape_pca$rotation[,1] %>% 
  as.data.frame() %>% 
  rename(loadings = ".") %>% 
  rownames_to_column(var = "traits")

pc2_loadings <- landscape_pca$rotation[,2] %>% 
  as.data.frame() %>% 
  rename(loadings = ".") %>% 
  rownames_to_column(var = "traits")

pc1_loadings_plot <- ggplot(pc1_loadings, aes(x = traits, y = loadings))+
  geom_col()+
  coord_flip()+
  theme_classic()

pc2_loadings_plot <- ggplot(pc2_loadings, aes(x = traits, y = loadings))+
  geom_col()+
  coord_flip()+
  theme_classic()
```

```{r}
total_species_survival_common <- total_species_survival %>% 
  mutate(species = case_when(species == "rhov" ~ "Sugar bush",
                             species == "adfa" ~ "Chamise",
                             species == "hear" ~ "toyon", 
                             species == "rhil" ~ "Hollyleaf redberry",
                             species == "mala" ~ "Laurel sumac",
                             species == "cecu" ~ "Buck brush",
                             species == "ceol" ~ "Hairy ceanothus",
                             species == "erfa" ~ "California buckwehat",
                             species == "saap" ~ "White sage",
                             species == "same" ~ "Black sage",
                             species == "arca" ~ "California sagebrush",
                             species == "sale" ~ "Purple sage",
                             species == "enca" ~ "California \n brittlebush"))

pc1_graph <- ggplot(total_species_survival_common, aes(x= PC1, y = proportion_alive))+
  geom_text(aes(label = species))+
  geom_text(aes(x = -3, y = 0.5, label = "r^2 == 0.377"), parse = T)+
  geom_text(aes(x = -3, y = 0.47, label = "p = 0.0255"))+
  geom_smooth(method = "glm")+
  theme_classic()+
  labs(y = "Proportion alive")
```


```{r}
load(here("data", "trait_model.rda"))

predicted_survival <- predict(trait_model, traits_pca_input, ncomp = 2) %>% 
  as.data.frame() %>% 
  rownames_to_column(var = "species") %>% 
  rename(predicted_survival = `alive_percent.2 comps`)

ggplot(predicted_survival, 
       aes(x = fct_reorder(species, predicted_survival, min), y = predicted_survival))+
  geom_point()+
  theme_minimal()


```

```{r}
predicted_actual_survival <- total_species_survival %>%
  mutate(actual_alive = proportion_alive) %>% 
  select(species, actual_alive) %>% 
  full_join(predicted_survival, by = "species") %>% 
  mutate(predicted_survival = predicted_survival/100)

ggplot(predicted_actual_survival, aes(x= predicted_survival, y = actual_alive))+
  geom_text(aes(label = species))+
  geom_abline(intercept = 0, slope = 1)+
  xlim(0,0.4)+
  theme_minimal()
```


